vst: "Axe-FX 5150 Block"
device: "Axe-FX 5150 Block"
control_type: MIDI
sweeps:
  - comment: "5150 Block"
    params:
    - name: ['Treble']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
      midi: 14
    - name: ['Mid']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
      midi: 13
    - name: ['Bass']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
      midi: 12
    - name: ['Drive']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
      midi: 11
