brand: "Fractal"
device: "FM3"
model: "Bosom Boost"
device_type: "Pedal"
data_type: "Synthetic"
preset_id: 6
controls:
  - name: 'Boost'
    value: 1
  - name: 'Tight'
    value: 2
sweeps:
  - comment: "Full Sweep"
    params:
    - name: ['Boost']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Tight']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
defaults:
  - name: "Level"
    value: 1.0
  - name: "Bass"
    value: 0.5
  - name: "Mid"
    value: 0.5
  - name: "Treble"
    value: 0.5

