brand: "Fractal"
device: "FM3"
model: "Esoteric RCB"
device_type: "Pedal"
data_type: "Synthetic"
preset_id: 14
controls:
  - name: 'Gain'
    value: 1
sweeps:
  - comment: "Full Sweep"
    params:
    - name: ['Gain']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
defaults:
  - name: "Level"
    value: 1.0
  - name: "Bass"
    value: 0.5
  - name: "Treble"
    value: 0.5


