brand: "Fractal"
device: "FM3"
model: "Horizon Precision Drive"
device_type: "Pedal"
data_type: "Synthetic"
preset_id: 28
controls:
  - name: 'Drive'
    value: 1
  - name: 'Attack'
    value: 2
  - name: 'Bright'
    value: 3
sweeps:
  - comment: "Full Sweep"
    params:
    - name: ['Drive']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Attack']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Bright']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
defaults:
  - name: "Level"
    value: 1.0


