brand: "Fractal"
device: "FM3"
model: "Timothy Mid"
device_type: "Pedal"
data_type: "Synthetic"
preset_id: 44
controls:
  - name: 'Gain'
    value: 1
  - name: 'Bass'
    value: 2
  - name: 'Treble'
    value: 2
sweeps:
  - comment: "Full Sweep"
    params:
    - name: ['Gain']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Bass']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Treble']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
defaults:
  - name: "Level"
    value: 1.0



