brand: "Fractal"
device: "FM3"
model: "Fryette D60 More"
device_type: "Amplifier"
data_type: "Synthetic"
preset_id: 102
controls:
  - name: 'Gain'
    value: 1
  - name: 'Overdrive'
    value: 2
  - name: 'Bass'
    value: 3
  - name: 'Mid'
    value: 4
  - name: 'Treble'
    value: 5
  - name: 'Depth'
    value: 6
sweeps:
  - comment: "Full Sweep"
    params:
    - name: ['Gain']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Overdrive']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Bass']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Mid']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Treble']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Depth']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
defaults:
  - name: "Presence"
    value: 0.5
  - name: "Input Trim"
    value: 0.5
  - name: "Master Volume"
    value: 0.5

