brand: "Fractal"
device: "FM3 - Axe-FX Wrecker Liverpool Block"
device_type: "Amplifier"
data_type: "Synthetic"
control_type: "MIDI"
controls:
  midi_channel: 0
  midi_mapping:
  - name: 'Treble'
    midi: 14
  - name: 'Mid'
    midi: 13
  - name: 'Bass'
    midi: 12
  - name: 'Drive'
    midi: 11
sweeps:
  - comment: "Tied Sweep 1-10"
    params:
    - name: ['Treble', 'Mid', 'Bass', 'Drive']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
  - comment: "Treble Sweep 1-10"
    params:
    - name: ['Bass', 'Mid', 'Drive']
      parameter_type: continuous
      min: 0.5
      max: 0.5
      step: 0.1
    - name: ['Treble']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
  - comment: "Mid Sweep 1-10"
    params:
    - name: ['Treble', 'Bass', 'Drive']
      parameter_type: continuous
      min: 0.5
      max: 0.5
      step: 0.1
    - name: ['Mid']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
  - comment: "Bass Sweep 1-10"
    params:
    - name: ['Treble', 'Mid', 'Drive']
      parameter_type: continuous
      min: 0.5
      max: 0.5
      step: 0.1
    - name: ['Bass']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
  - comment: "Drive Sweep 1-10"
    params:
    - name: ['Treble', 'Mid', 'Bass']
      parameter_type: continuous
      min: 0.5
      max: 0.5
      step: 0.1
    - name: ['Drive']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
  - comment: "Full Sweep"
    params:
    - name: ['Treble']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Mid']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Bass']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
    - name: ['Drive']
      parameter_type: continuous
      min: 0.1
      max: 1.0
      step: 0.1
defaults:
  - name: "Presence"
    value: 0.5
  - name: "Bright Switch"
    value: 0.0



